apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-nginx
  template:
    metadata:
      labels:
        app: hello-nginx
    spec:
      containers:
        - name: nginx
          image: joelgaikwad/hello-nginx-harness:<+pipeline.sequenceId>
          imagePullPolicy: Always
          ports:
            - containerPort: 80
